### ISSUE TITLE
Task spawning missing in "Shared state" section

### ISSUE THREAD

**Issue by rdettai** [tokio-rs/website#489] opened 2020-09-28 08:35 UTC
In the shared state, the processing is simply awaited, but I believe it should be executed in a new Task, like it was introduced in the previous section.

PR: https://github.com/tokio-rs/website/pull/488

**Comment by timKraeuter** [comment] 2024-04-14 08:41
Should this be closed since the PR is merged and the problem is fixed?

**Closed** 2024-04-14 19:09 UTC
